# Generated by Django 4.2.7 on 2025-08-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_retention_days', models.IntegerField(default=90)),
                ('auto_archive_enabled', models.BooleanField(default=True)),
                ('permanent_sessions_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_retention_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_config', models.JSONField(default=dict, help_text='LLM model configuration')),
                ('context_window', models.IntegerField(default=4000, help_text='Context window size')),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt for the session')),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('retention_days', models.IntegerField(default=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('tokens', models.IntegerField(default=0, help_text='Token count for this message')),
                ('model_used', models.CharField(blank=True, help_text='LLM model used for generation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_ms', models.IntegerField(blank=True, help_text='Generation time in milliseconds', null=True)),
                ('tool_calls', models.JSONField(default=list, help_text='Tool calls made in this message')),
                ('emotion_snapshot', models.CharField(blank=True, help_text='Emotion detected in message', max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Additional message metadata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chat_chatse_user_id_40a24e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_at'], name='chat_chatse_created_8e9e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_chatme_session_70d41b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'created_at'], name='chat_chatme_role_5fee23_idx'),
        ),
    ]
